export const OFF_SCREEN_TOP = 30;
export const OFF_SCREEN_BOTTOM = -45;
export const OFF_SCREEN_LEFT = -45;
export const OFF_SCREEN_RIGHT = 45;
export const SCREEN_LEFT_EDGE = -30;
export const SCREEN_RIGHT_EDGE = 30;
export const SCREEN_TOP_EDGE = 20;
export const SCREEN_BOTTOM_EDGE = -15;
export var HEIGHT = 10;
export const SPAWN_ENEMY_INTERVAL = 1500; // milliseconds
export const SPAWN_HEALTHPACK_INTERVAL = 1500 // milliseconds
export const SHOOT_COOLDOWN = 500;// decresase every X milliseconds
export const MIN_ENEMY_SPEED = -0.1;
export const MAX_ENEMY_SPEED = -0.3;
export const PROJECTILE_SPEED = 0.9;
export const PLAYER_SPEED = 30;
export const PLANE_SPEED = 0.1;